export const flightData = {
    "flights": [
        {
            "ident": "BAW92",
            "ident_icao": "BAW92",
            "ident_iata": "BA92",
            "actual_runway_off": null,
            "actual_runway_on": null,
            "fa_flight_id": "BAW92-1738823831-airline-1897p",
            "operator": "BAW",
            "operator_icao": "BAW",
            "operator_iata": "BA",
            "flight_number": "92",
            "registration": null,
            "atc_ident": null,
            "inbound_fa_flight_id": null,
            "codeshares": [
                "FIN5992",
                "EIN8792",
                "AAL6917",
                "IBE3528"
            ],
            "codeshares_iata": [
                "AY5992",
                "EI8792",
                "AA6917",
                "IB3528"
            ],
            "blocked": false,
            "diverted": false,
            "cancelled": false,
            "position_only": false,
            "origin": {
                "code": "CYYZ",
                "code_icao": "CYYZ",
                "code_iata": "YYZ",
                "code_lid": null,
                "timezone": "America/Toronto",
                "name": "Toronto Pearson Int'l",
                "city": "Toronto",
                "airport_info_url": "/airports/CYYZ"
            },
            "destination": {
                "code": "EGLL",
                "code_icao": "EGLL",
                "code_iata": "LHR",
                "code_lid": null,
                "timezone": "Europe/London",
                "name": "London Heathrow",
                "city": "London",
                "airport_info_url": "/airports/EGLL"
            },
            "departure_delay": 0,
            "arrival_delay": 0,
            "filed_ete": 24900,
            "foresight_predictions_available": false,
            "scheduled_out": "2025-02-08T23:00:00Z",
            "estimated_out": "2025-02-08T23:00:00Z",
            "actual_out": null,
            "scheduled_off": "2025-02-08T23:10:00Z",
            "estimated_off": "2025-02-08T23:10:00Z",
            "actual_off": null,
            "scheduled_on": "2025-02-09T06:05:00Z",
            "estimated_on": "2025-02-09T06:05:00Z",
            "actual_on": null,
            "scheduled_in": "2025-02-09T06:15:00Z",
            "estimated_in": "2025-02-09T06:15:00Z",
            "actual_in": null,
            "progress_percent": 0,
            "status": "Scheduled",
            "aircraft_type": "A35K",
            "route_distance": 3550,
            "filed_airspeed": 447,
            "filed_altitude": null,
            "route": null,
            "baggage_claim": null,
            "seats_cabin_business": null,
            "seats_cabin_coach": null,
            "seats_cabin_first": null,
            "gate_origin": null,
            "gate_destination": null,
            "terminal_origin": "3",
            "terminal_destination": "5",
            "type": "Airline"
        },
        {
            "ident": "BAW92",
            "ident_icao": "BAW92",
            "ident_iata": "BA92",
            "actual_runway_off": null,
            "actual_runway_on": null,
            "fa_flight_id": "BAW92-1738737895-airline-712p",
            "operator": "BAW",
            "operator_icao": "BAW",
            "operator_iata": "BA",
            "flight_number": "92",
            "registration": "G-YMMK",
            "atc_ident": null,
            "inbound_fa_flight_id": "BAW93-1738737895-airline-713p",
            "codeshares": [
                "FIN5992",
                "EIN8792",
                "AAL6917",
                "IBE3528"
            ],
            "codeshares_iata": [
                "AY5992",
                "EI8792",
                "AA6917",
                "IB3528"
            ],
            "blocked": false,
            "diverted": false,
            "cancelled": false,
            "position_only": false,
            "origin": {
                "code": "CYYZ",
                "code_icao": "CYYZ",
                "code_iata": "YYZ",
                "code_lid": null,
                "timezone": "America/Toronto",
                "name": "Toronto Pearson Int'l",
                "city": "Toronto",
                "airport_info_url": "/airports/CYYZ"
            },
            "destination": {
                "code": "EGLL",
                "code_icao": "EGLL",
                "code_iata": "LHR",
                "code_lid": null,
                "timezone": "Europe/London",
                "name": "London Heathrow",
                "city": "London",
                "airport_info_url": "/airports/EGLL"
            },
            "departure_delay": 0,
            "arrival_delay": 0,
            "filed_ete": 24900,
            "foresight_predictions_available": false,
            "scheduled_out": "2025-02-07T23:00:00Z",
            "estimated_out": "2025-02-07T23:00:00Z",
            "actual_out": null,
            "scheduled_off": "2025-02-07T23:10:00Z",
            "estimated_off": "2025-02-07T23:10:00Z",
            "actual_off": null,
            "scheduled_on": "2025-02-08T06:05:00Z",
            "estimated_on": "2025-02-08T06:05:00Z",
            "actual_on": null,
            "scheduled_in": "2025-02-08T06:15:00Z",
            "estimated_in": "2025-02-08T06:15:00Z",
            "actual_in": null,
            "progress_percent": 0,
            "status": "Scheduled",
            "aircraft_type": "B772",
            "route_distance": 3618,
            "filed_airspeed": 479,
            "filed_altitude": 410,
            "route": "VERDO7 LORKA Q907 MIILS N269A JOOPY NATT DOGAL NATT BEXET ENJEX AVZAC INFEC JETZI AMFUL OCTIZ P2 SIRIC",
            "baggage_claim": null,
            "seats_cabin_business": null,
            "seats_cabin_coach": null,
            "seats_cabin_first": null,
            "gate_origin": null,
            "gate_destination": null,
            "terminal_origin": "3",
            "terminal_destination": "5",
            "type": "Airline"
        },
        {
            "ident": "BAW92",
            "ident_icao": "BAW92",
            "ident_iata": "BA92",
            "actual_runway_off": "23",
            "actual_runway_on": null,
            "fa_flight_id": "BAW92-1738651568-airline-1208p",
            "operator": "BAW",
            "operator_icao": "BAW",
            "operator_iata": "BA",
            "flight_number": "92",
            "registration": "G-VIIG",
            "atc_ident": "BAW5CA",
            "inbound_fa_flight_id": "BAW93-1738651568-airline-1209p",
            "codeshares": [
                "FIN5992",
                "EIN8792",
                "AAL6917",
                "IBE3528"
            ],
            "codeshares_iata": [
                "AY5992",
                "EI8792",
                "AA6917",
                "IB3528"
            ],
            "blocked": false,
            "diverted": false,
            "cancelled": false,
            "position_only": false,
            "origin": {
                "code": "CYYZ",
                "code_icao": "CYYZ",
                "code_iata": "YYZ",
                "code_lid": null,
                "timezone": "America/Toronto",
                "name": "Toronto Pearson Int'l",
                "city": "Toronto",
                "airport_info_url": "/airports/CYYZ"
            },
            "destination": {
                "code": "EGLL",
                "code_icao": "EGLL",
                "code_iata": "LHR",
                "code_lid": null,
                "timezone": "Europe/London",
                "name": "London Heathrow",
                "city": "London",
                "airport_info_url": "/airports/EGLL"
            },
            "departure_delay": 0,
            "arrival_delay": -960,
            "filed_ete": 22980,
            "foresight_predictions_available": true,
            "scheduled_out": "2025-02-06T22:40:00Z",
            "estimated_out": "2025-02-06T22:40:00Z",
            "actual_out": "2025-02-06T22:40:00Z",
            "scheduled_off": "2025-02-06T22:50:00Z",
            "estimated_off": "2025-02-06T23:05:27Z",
            "actual_off": "2025-02-06T23:04:00Z",
            "scheduled_on": "2025-02-07T05:13:00Z",
            "estimated_on": "2025-02-07T05:29:00Z",
            "actual_on": null,
            "scheduled_in": "2025-02-07T05:55:00Z",
            "estimated_in": "2025-02-07T05:39:00Z",
            "actual_in": null,
            "progress_percent": 81,
            "status": "En Route / On Time",
            "aircraft_type": "B78X",
            "route_distance": 3600,
            "filed_airspeed": 440,
            "filed_altitude": 310,
            "route": "VERDO7 LORKA Q907 MIILS N329B ELSIR NATT 5000N/05000W NATT 5400N/03000W NATT RESNO NATT NETKI BOFUM Q37 BAVUD Q37 MALUD Q38 NUGRA NUGRA1H",
            "baggage_claim": null,
            "seats_cabin_business": null,
            "seats_cabin_coach": null,
            "seats_cabin_first": null,
            "gate_origin": null,
            "gate_destination": null,
            "terminal_origin": "3",
            "terminal_destination": "5",
            "type": "Airline"
        },
        {
            "ident": "BAW92",
            "ident_icao": "BAW92",
            "ident_iata": "BA92",
            "actual_runway_off": "05",
            "actual_runway_on": "09L",
            "fa_flight_id": "BAW92-1738565051-airline-1341p",
            "operator": "BAW",
            "operator_icao": "BAW",
            "operator_iata": "BA",
            "flight_number": "92",
            "registration": "G-ZBLB",
            "atc_ident": "BAW5CA",
            "inbound_fa_flight_id": "BAW93-1738565051-airline-1342p",
            "codeshares": [
                "FIN5992",
                "EIN8792",
                "AAL6917",
                "IBE3528"
            ],
            "codeshares_iata": [
                "AY5992",
                "EI8792",
                "AA6917",
                "IB3528"
            ],
            "blocked": false,
            "diverted": false,
            "cancelled": false,
            "position_only": false,
            "origin": {
                "code": "CYYZ",
                "code_icao": "CYYZ",
                "code_iata": "YYZ",
                "code_lid": null,
                "timezone": "America/Toronto",
                "name": "Toronto Pearson Int'l",
                "city": "Toronto",
                "airport_info_url": "/airports/CYYZ"
            },
            "destination": {
                "code": "EGLL",
                "code_icao": "EGLL",
                "code_iata": "LHR",
                "code_lid": null,
                "timezone": "Europe/London",
                "name": "London Heathrow",
                "city": "London",
                "airport_info_url": "/airports/EGLL"
            },
            "departure_delay": -180,
            "arrival_delay": -1920,
            "filed_ete": 22380,
            "foresight_predictions_available": true,
            "scheduled_out": "2025-02-05T22:40:00Z",
            "estimated_out": "2025-02-05T22:40:00Z",
            "actual_out": "2025-02-05T22:37:00Z",
            "scheduled_off": "2025-02-05T22:50:00Z",
            "estimated_off": "2025-02-05T23:00:07Z",
            "actual_off": "2025-02-05T22:59:00Z",
            "scheduled_on": "2025-02-06T05:03:00Z",
            "estimated_on": "2025-02-06T05:14:26Z",
            "actual_on": "2025-02-06T05:14:26Z",
            "scheduled_in": "2025-02-06T05:55:00Z",
            "estimated_in": "2025-02-06T05:21:00Z",
            "actual_in": "2025-02-06T05:23:00Z",
            "progress_percent": 100,
            "status": "Arrived / Gate Arrival",
            "aircraft_type": "B78X",
            "route_distance": 3644,
            "filed_airspeed": 477,
            "filed_altitude": 370,
            "route": "VERDO7 LORKA Q907 MIILS N269A JOOPY NATT 5400N/03000W NATT RESNO NATT NETKI LIFFY NUGRA NUGRA1H",
            "baggage_claim": "3",
            "seats_cabin_business": null,
            "seats_cabin_coach": null,
            "seats_cabin_first": null,
            "gate_origin": null,
            "gate_destination": null,
            "terminal_origin": "3",
            "terminal_destination": "5",
            "type": "Airline"
        },
        {
            "ident": "BAW92",
            "ident_icao": "BAW92",
            "ident_iata": "BA92",
            "actual_runway_off": "05",
            "actual_runway_on": "27R",
            "fa_flight_id": "BAW92-1738479874-airline-1368p",
            "operator": "BAW",
            "operator_icao": "BAW",
            "operator_iata": "BA",
            "flight_number": "92",
            "registration": "G-ZBKP",
            "atc_ident": "BAW5CA",
            "inbound_fa_flight_id": "BAW93-1738479874-airline-1369p",
            "codeshares": [
                "FIN5992",
                "EIN8792",
                "AAL6917",
                "IBE3528"
            ],
            "codeshares_iata": [
                "AY5992",
                "EI8792",
                "AA6917",
                "IB3528"
            ],
            "blocked": false,
            "diverted": false,
            "cancelled": false,
            "position_only": false,
            "origin": {
                "code": "CYYZ",
                "code_icao": "CYYZ",
                "code_iata": "YYZ",
                "code_lid": null,
                "timezone": "America/Toronto",
                "name": "Toronto Pearson Int'l",
                "city": "Toronto",
                "airport_info_url": "/airports/CYYZ"
            },
            "destination": {
                "code": "EGLL",
                "code_icao": "EGLL",
                "code_iata": "LHR",
                "code_lid": null,
                "timezone": "Europe/London",
                "name": "London Heathrow",
                "city": "London",
                "airport_info_url": "/airports/EGLL"
            },
            "departure_delay": 1020,
            "arrival_delay": 300,
            "filed_ete": 22080,
            "foresight_predictions_available": true,
            "scheduled_out": "2025-02-04T23:00:00Z",
            "estimated_out": "2025-02-04T23:00:00Z",
            "actual_out": "2025-02-04T23:17:00Z",
            "scheduled_off": "2025-02-04T23:10:00Z",
            "estimated_off": "2025-02-05T00:02:14Z",
            "actual_off": "2025-02-05T00:00:00Z",
            "scheduled_on": "2025-02-05T05:18:00Z",
            "estimated_on": "2025-02-05T06:13:57Z",
            "actual_on": "2025-02-05T06:13:57Z",
            "scheduled_in": "2025-02-05T06:15:00Z",
            "estimated_in": "2025-02-05T06:20:00Z",
            "actual_in": "2025-02-05T06:20:00Z",
            "progress_percent": 100,
            "status": "Arrived / Gate Arrival",
            "aircraft_type": "B789",
            "route_distance": 3631,
            "filed_airspeed": 485,
            "filed_altitude": 390,
            "route": "VERDO7 LORKA Q907 MIILS N329B ELSIR NATS 5000N/05000W NATS 5400N/03000W NATS RESNO NATS NETKI NIBOG KELLY L10 CASEL L10 PENIL L10 WAL UY53 NUGRA NUGRA1H",
            "baggage_claim": "9",
            "seats_cabin_business": null,
            "seats_cabin_coach": null,
            "seats_cabin_first": null,
            "gate_origin": null,
            "gate_destination": null,
            "terminal_origin": "3",
            "terminal_destination": "5",
            "type": "Airline"
        },
        {
            "ident": "BAW92",
            "ident_icao": "BAW92",
            "ident_iata": "BA92",
            "actual_runway_off": "05",
            "actual_runway_on": "27R",
            "fa_flight_id": "BAW92-1738389536-airline-1292p",
            "operator": "BAW",
            "operator_icao": "BAW",
            "operator_iata": "BA",
            "flight_number": "92",
            "registration": "G-ZBKB",
            "atc_ident": "BAW5CA",
            "inbound_fa_flight_id": "BAW93-1738389536-airline-1293p",
            "codeshares": [
                "FIN5992",
                "EIN8792",
                "AAL6917",
                "IBE3528"
            ],
            "codeshares_iata": [
                "AY5992",
                "EI8792",
                "AA6917",
                "IB3528"
            ],
            "blocked": false,
            "diverted": false,
            "cancelled": false,
            "position_only": false,
            "origin": {
                "code": "CYYZ",
                "code_icao": "CYYZ",
                "code_iata": "YYZ",
                "code_lid": null,
                "timezone": "America/Toronto",
                "name": "Toronto Pearson Int'l",
                "city": "Toronto",
                "airport_info_url": "/airports/CYYZ"
            },
            "destination": {
                "code": "EGLL",
                "code_icao": "EGLL",
                "code_iata": "LHR",
                "code_lid": null,
                "timezone": "Europe/London",
                "name": "London Heathrow",
                "city": "London",
                "airport_info_url": "/airports/EGLL"
            },
            "departure_delay": -300,
            "arrival_delay": 900,
            "filed_ete": 22440,
            "foresight_predictions_available": true,
            "scheduled_out": "2025-02-03T23:00:00Z",
            "estimated_out": "2025-02-03T23:00:00Z",
            "actual_out": "2025-02-03T22:55:00Z",
            "scheduled_off": "2025-02-03T23:10:00Z",
            "estimated_off": "2025-02-03T23:50:17Z",
            "actual_off": "2025-02-03T23:48:00Z",
            "scheduled_on": "2025-02-04T05:24:00Z",
            "estimated_on": "2025-02-04T06:21:59Z",
            "actual_on": "2025-02-04T06:21:59Z",
            "scheduled_in": "2025-02-04T06:15:00Z",
            "estimated_in": "2025-02-04T06:32:07Z",
            "actual_in": "2025-02-04T06:30:00Z",
            "progress_percent": 100,
            "status": "Arrived / Gate Arrival",
            "aircraft_type": "B789",
            "route_distance": 3581,
            "filed_airspeed": 439,
            "filed_altitude": 330,
            "route": "VERDO7 LORKA Q907 ATENE TAFFY N451A TUDEP 5200N/05000W 5330N/04000W 5400N/03000W 5500N/02000W RESNO NETKI BOFUM Q37 MALUD Q38 NUGRA NUGRA1H",
            "baggage_claim": null,
            "seats_cabin_business": null,
            "seats_cabin_coach": null,
            "seats_cabin_first": null,
            "gate_origin": null,
            "gate_destination": null,
            "terminal_origin": "3",
            "terminal_destination": "5",
            "type": "Airline"
        },
        {
            "ident": "BAW92",
            "ident_icao": "BAW92",
            "ident_iata": "BA92",
            "actual_runway_off": "06L",
            "actual_runway_on": "27L",
            "fa_flight_id": "BAW92-1738304183-airline-714p",
            "operator": "BAW",
            "operator_icao": "BAW",
            "operator_iata": "BA",
            "flight_number": "92",
            "registration": "G-VIID",
            "atc_ident": "BAW5CA",
            "inbound_fa_flight_id": "BAW93-1738304183-airline-715p",
            "codeshares": [
                "FIN5992",
                "EIN8792",
                "AAL6917",
                "IBE3528"
            ],
            "codeshares_iata": [
                "AY5992",
                "EI8792",
                "AA6917",
                "IB3528"
            ],
            "blocked": false,
            "diverted": false,
            "cancelled": false,
            "position_only": false,
            "origin": {
                "code": "CYYZ",
                "code_icao": "CYYZ",
                "code_iata": "YYZ",
                "code_lid": null,
                "timezone": "America/Toronto",
                "name": "Toronto Pearson Int'l",
                "city": "Toronto",
                "airport_info_url": "/airports/CYYZ"
            },
            "destination": {
                "code": "EGLL",
                "code_icao": "EGLL",
                "code_iata": "LHR",
                "code_lid": null,
                "timezone": "Europe/London",
                "name": "London Heathrow",
                "city": "London",
                "airport_info_url": "/airports/EGLL"
            },
            "departure_delay": 3900,
            "arrival_delay": 3420,
            "filed_ete": 22260,
            "foresight_predictions_available": true,
            "scheduled_out": "2025-02-02T23:00:00Z",
            "estimated_out": "2025-02-02T23:51:00Z",
            "actual_out": "2025-02-03T00:05:00Z",
            "scheduled_off": "2025-02-02T23:10:00Z",
            "estimated_off": "2025-02-03T00:52:57Z",
            "actual_off": "2025-02-03T00:51:00Z",
            "scheduled_on": "2025-02-03T05:21:00Z",
            "estimated_on": "2025-02-03T07:05:44Z",
            "actual_on": "2025-02-03T07:05:44Z",
            "scheduled_in": "2025-02-03T06:15:00Z",
            "estimated_in": "2025-02-03T07:12:00Z",
            "actual_in": "2025-02-03T07:12:00Z",
            "progress_percent": 100,
            "status": "Arrived / Delayed",
            "aircraft_type": "B772",
            "route_distance": 3624,
            "filed_airspeed": 486,
            "filed_altitude": 370,
            "route": "VERDO7 LORKA Q907 MIILS N269A JOOPY NATT DOGAL NATT BEXET ENJEX AVZAC INFEC JETZI AMFUL OCTIZ P2 SIRIC SIRIC1H",
            "baggage_claim": "5",
            "seats_cabin_business": null,
            "seats_cabin_coach": null,
            "seats_cabin_first": null,
            "gate_origin": null,
            "gate_destination": null,
            "terminal_origin": "3",
            "terminal_destination": "5",
            "type": "Airline"
        },
        {
            "ident": "BAW92",
            "ident_icao": "BAW92",
            "ident_iata": "BA92",
            "actual_runway_off": "05",
            "actual_runway_on": "09R",
            "fa_flight_id": "BAW92-1738218576-airline-1017p",
            "operator": "BAW",
            "operator_icao": "BAW",
            "operator_iata": "BA",
            "flight_number": "92",
            "registration": "G-YMMK",
            "atc_ident": "BAW5CA",
            "inbound_fa_flight_id": "BAW93-1738218576-airline-1018p",
            "codeshares": [
                "FIN5992",
                "EIN8792",
                "AAL6917",
                "IBE3528"
            ],
            "codeshares_iata": [
                "AY5992",
                "EI8792",
                "AA6917",
                "IB3528"
            ],
            "blocked": false,
            "diverted": false,
            "cancelled": false,
            "position_only": false,
            "origin": {
                "code": "CYYZ",
                "code_icao": "CYYZ",
                "code_iata": "YYZ",
                "code_lid": null,
                "timezone": "America/Toronto",
                "name": "Toronto Pearson Int'l",
                "city": "Toronto",
                "airport_info_url": "/airports/CYYZ"
            },
            "destination": {
                "code": "EGLL",
                "code_icao": "EGLL",
                "code_iata": "LHR",
                "code_lid": null,
                "timezone": "Europe/London",
                "name": "London Heathrow",
                "city": "London",
                "airport_info_url": "/airports/EGLL"
            },
            "departure_delay": 60,
            "arrival_delay": -240,
            "filed_ete": 21420,
            "foresight_predictions_available": true,
            "scheduled_out": "2025-02-01T23:00:00Z",
            "estimated_out": "2025-02-01T23:00:00Z",
            "actual_out": "2025-02-01T23:01:00Z",
            "scheduled_off": "2025-02-01T23:10:00Z",
            "estimated_off": "2025-02-01T23:24:45Z",
            "actual_off": "2025-02-01T23:24:45Z",
            "scheduled_on": "2025-02-02T05:07:00Z",
            "estimated_on": "2025-02-02T06:03:14Z",
            "actual_on": "2025-02-02T06:03:14Z",
            "scheduled_in": "2025-02-02T06:15:00Z",
            "estimated_in": "2025-02-02T06:10:00Z",
            "actual_in": "2025-02-02T06:11:00Z",
            "progress_percent": 100,
            "status": "Arrived / Gate Arrival",
            "aircraft_type": "B772",
            "route_distance": 3616,
            "filed_airspeed": 465,
            "filed_altitude": 350,
            "route": "VERDO7 LORKA Q907 ATENE Q907 MIILS N269A JOOPY NATU MALOT NATU GISTI ENJEX AVZAC INFEC JETZI AMFUL OCTIZ P2 SIRIC SIRIC1H",
            "baggage_claim": "8",
            "seats_cabin_business": null,
            "seats_cabin_coach": null,
            "seats_cabin_first": null,
            "gate_origin": null,
            "gate_destination": null,
            "terminal_origin": "3",
            "terminal_destination": "5",
            "type": "Airline"
        },
        {
            "ident": "BAW92",
            "ident_icao": "BAW92",
            "ident_iata": "BA92",
            "actual_runway_off": "05",
            "actual_runway_on": "09L",
            "fa_flight_id": "BAW92-1738135601-airline-1289p",
            "operator": "BAW",
            "operator_icao": "BAW",
            "operator_iata": "BA",
            "flight_number": "92",
            "registration": "G-VIIS",
            "atc_ident": "BAW5CA",
            "inbound_fa_flight_id": "BAW93-1738135601-airline-1290p",
            "codeshares": [
                "FIN5992",
                "EIN8792",
                "AAL6917",
                "IBE3528"
            ],
            "codeshares_iata": [
                "AY5992",
                "EI8792",
                "AA6917",
                "IB3528"
            ],
            "blocked": false,
            "diverted": false,
            "cancelled": false,
            "position_only": false,
            "origin": {
                "code": "CYYZ",
                "code_icao": "CYYZ",
                "code_iata": "YYZ",
                "code_lid": null,
                "timezone": "America/Toronto",
                "name": "Toronto Pearson Int'l",
                "city": "Toronto",
                "airport_info_url": "/airports/CYYZ"
            },
            "destination": {
                "code": "EGLL",
                "code_icao": "EGLL",
                "code_iata": "LHR",
                "code_lid": null,
                "timezone": "Europe/London",
                "name": "London Heathrow",
                "city": "London",
                "airport_info_url": "/airports/EGLL"
            },
            "departure_delay": 0,
            "arrival_delay": -240,
            "filed_ete": 22020,
            "foresight_predictions_available": true,
            "scheduled_out": "2025-01-31T23:00:00Z",
            "estimated_out": "2025-01-31T23:00:00Z",
            "actual_out": "2025-01-31T23:00:00Z",
            "scheduled_off": "2025-01-31T23:10:00Z",
            "estimated_off": "2025-01-31T23:44:11Z",
            "actual_off": "2025-01-31T23:42:00Z",
            "scheduled_on": "2025-02-01T05:17:00Z",
            "estimated_on": "2025-02-01T06:05:25Z",
            "actual_on": "2025-02-01T06:05:25Z",
            "scheduled_in": "2025-02-01T06:15:00Z",
            "estimated_in": "2025-02-01T06:13:41Z",
            "actual_in": "2025-02-01T06:11:00Z",
            "progress_percent": 100,
            "status": "Arrived / Gate Arrival",
            "aircraft_type": "B772",
            "route_distance": 3695,
            "filed_airspeed": 472,
            "filed_altitude": 350,
            "route": "VERDO7 LORKA Q907 MIILS N155A PORTI NATV 4700N/05000W NATV MALOT NATV GISTI ENJEX AVZAC INFEC JETZI AMFUL OCTIZ P2 SIRIC SIRIC1H",
            "baggage_claim": null,
            "seats_cabin_business": null,
            "seats_cabin_coach": null,
            "seats_cabin_first": null,
            "gate_origin": null,
            "gate_destination": null,
            "terminal_origin": "3",
            "terminal_destination": "5",
            "type": "Airline"
        },
        {
            "ident": "BAW92",
            "ident_icao": "BAW92",
            "ident_iata": "BA92",
            "actual_runway_off": "24R",
            "actual_runway_on": "27R",
            "fa_flight_id": "BAW92-1738049000-airline-874p",
            "operator": "BAW",
            "operator_icao": "BAW",
            "operator_iata": "BA",
            "flight_number": "92",
            "registration": "G-ZBKA",
            "atc_ident": "BAW5CA",
            "inbound_fa_flight_id": "BAW93-1738049000-airline-875p",
            "codeshares": [
                "FIN5992",
                "EIN8792",
                "AAL6917",
                "IBE3528"
            ],
            "codeshares_iata": [
                "AY5992",
                "EI8792",
                "AA6917",
                "IB3528"
            ],
            "blocked": false,
            "diverted": false,
            "cancelled": false,
            "position_only": false,
            "origin": {
                "code": "CYYZ",
                "code_icao": "CYYZ",
                "code_iata": "YYZ",
                "code_lid": null,
                "timezone": "America/Toronto",
                "name": "Toronto Pearson Int'l",
                "city": "Toronto",
                "airport_info_url": "/airports/CYYZ"
            },
            "destination": {
                "code": "EGLL",
                "code_icao": "EGLL",
                "code_iata": "LHR",
                "code_lid": null,
                "timezone": "Europe/London",
                "name": "London Heathrow",
                "city": "London",
                "airport_info_url": "/airports/EGLL"
            },
            "departure_delay": -60,
            "arrival_delay": -1500,
            "filed_ete": 22200,
            "foresight_predictions_available": true,
            "scheduled_out": "2025-01-30T22:40:00Z",
            "estimated_out": "2025-01-30T22:40:00Z",
            "actual_out": "2025-01-30T22:39:00Z",
            "scheduled_off": "2025-01-30T22:50:00Z",
            "estimated_off": "2025-01-30T23:09:13Z",
            "actual_off": "2025-01-30T23:07:00Z",
            "scheduled_on": "2025-01-31T05:00:00Z",
            "estimated_on": "2025-01-31T05:23:20Z",
            "actual_on": "2025-01-31T05:23:20Z",
            "scheduled_in": "2025-01-31T05:55:00Z",
            "estimated_in": "2025-01-31T05:28:00Z",
            "actual_in": "2025-01-31T05:30:00Z",
            "progress_percent": 100,
            "status": "Arrived / Gate Arrival",
            "aircraft_type": "B789",
            "route_distance": 3612,
            "filed_airspeed": 462,
            "filed_altitude": 350,
            "route": "VERDO7 LORKA Q907 IMAMA Q907 MIILS N329B ELSIR NATV DOGAL NATV BEXET ENJEX AVZAC INFEC JETZI AMFUL OCTIZ P2 SIRIC SIRIC1H",
            "baggage_claim": null,
            "seats_cabin_business": null,
            "seats_cabin_coach": null,
            "seats_cabin_first": null,
            "gate_origin": null,
            "gate_destination": null,
            "terminal_origin": "3",
            "terminal_destination": "5",
            "type": "Airline"
        },
        {
            "ident": "BAW92",
            "ident_icao": "BAW92",
            "ident_iata": "BA92",
            "actual_runway_off": null,
            "actual_runway_on": null,
            "fa_flight_id": "BAW92-1737960598-airline-1251p",
            "operator": "BAW",
            "operator_icao": "BAW",
            "operator_iata": "BA",
            "flight_number": "92",
            "registration": null,
            "atc_ident": "BAW5CA",
            "inbound_fa_flight_id": null,
            "codeshares": [
                "FIN5992",
                "EIN8792",
                "AAL6917",
                "IBE3528"
            ],
            "codeshares_iata": [
                "AY5992",
                "EI8792",
                "AA6917",
                "IB3528"
            ],
            "blocked": false,
            "diverted": false,
            "cancelled": true,
            "position_only": false,
            "origin": {
                "code": "CYYZ",
                "code_icao": "CYYZ",
                "code_iata": "YYZ",
                "code_lid": null,
                "timezone": "America/Toronto",
                "name": "Toronto Pearson Int'l",
                "city": "Toronto",
                "airport_info_url": "/airports/CYYZ"
            },
            "destination": {
                "code": "EGLL",
                "code_icao": "EGLL",
                "code_iata": "LHR",
                "code_lid": null,
                "timezone": "Europe/London",
                "name": "London Heathrow",
                "city": "London",
                "airport_info_url": "/airports/EGLL"
            },
            "departure_delay": 13800,
            "arrival_delay": 10740,
            "filed_ete": 21840,
            "foresight_predictions_available": true,
            "scheduled_out": "2025-01-29T22:40:00Z",
            "estimated_out": "2025-01-30T02:30:00Z",
            "actual_out": null,
            "scheduled_off": "2025-01-29T22:50:00Z",
            "estimated_off": "2025-01-30T02:40:00Z",
            "actual_off": null,
            "scheduled_on": "2025-01-30T04:54:00Z",
            "estimated_on": null,
            "actual_on": null,
            "scheduled_in": "2025-01-30T05:55:00Z",
            "estimated_in": "2025-01-30T08:54:00Z",
            "actual_in": null,
            "progress_percent": 100,
            "status": "Cancelled",
            "aircraft_type": "B789",
            "route_distance": 3650,
            "filed_airspeed": 492,
            "filed_altitude": 390,
            "route": "VERDO7 LORKA Q907 MIILS N211E NICSO NATV DOGAL NATV BEXET ENJEX AVZAC INFEC JETZI AMFUL OCTIZ P2 SIRIC SIRIC1H",
            "baggage_claim": null,
            "seats_cabin_business": null,
            "seats_cabin_coach": null,
            "seats_cabin_first": null,
            "gate_origin": null,
            "gate_destination": null,
            "terminal_origin": "3",
            "terminal_destination": "5",
            "type": "Airline"
        },
        {
            "ident": "BAW92",
            "ident_icao": "BAW92",
            "ident_iata": "BA92",
            "actual_runway_off": "24R",
            "actual_runway_on": "27R",
            "fa_flight_id": "BAW92-1737873627-airline-1339p",
            "operator": "BAW",
            "operator_icao": "BAW",
            "operator_iata": "BA",
            "flight_number": "92",
            "registration": "G-ZBJB",
            "atc_ident": "BAW5CA",
            "inbound_fa_flight_id": "BAW93-1737873627-airline-1340p",
            "codeshares": [
                "FIN5992",
                "EIN8792",
                "AAL6917",
                "IBE3528"
            ],
            "codeshares_iata": [
                "AY5992",
                "EI8792",
                "AA6917",
                "IB3528"
            ],
            "blocked": false,
            "diverted": false,
            "cancelled": false,
            "position_only": false,
            "origin": {
                "code": "CYYZ",
                "code_icao": "CYYZ",
                "code_iata": "YYZ",
                "code_lid": null,
                "timezone": "America/Toronto",
                "name": "Toronto Pearson Int'l",
                "city": "Toronto",
                "airport_info_url": "/airports/CYYZ"
            },
            "destination": {
                "code": "EGLL",
                "code_icao": "EGLL",
                "code_iata": "LHR",
                "code_lid": null,
                "timezone": "Europe/London",
                "name": "London Heathrow",
                "city": "London",
                "airport_info_url": "/airports/EGLL"
            },
            "departure_delay": 720,
            "arrival_delay": 2880,
            "filed_ete": 22380,
            "foresight_predictions_available": true,
            "scheduled_out": "2025-01-28T23:00:00Z",
            "estimated_out": "2025-01-28T23:00:00Z",
            "actual_out": "2025-01-28T23:12:00Z",
            "scheduled_off": "2025-01-28T23:10:00Z",
            "estimated_off": "2025-01-29T00:40:13Z",
            "actual_off": "2025-01-29T00:39:00Z",
            "scheduled_on": "2025-01-29T05:23:00Z",
            "estimated_on": "2025-01-29T06:52:14Z",
            "actual_on": "2025-01-29T06:52:14Z",
            "scheduled_in": "2025-01-29T06:15:00Z",
            "estimated_in": "2025-01-29T06:57:00Z",
            "actual_in": "2025-01-29T07:03:00Z",
            "progress_percent": 100,
            "status": "Arrived / Delayed",
            "aircraft_type": "B788",
            "route_distance": 3574,
            "filed_airspeed": 488,
            "filed_altitude": 390,
            "route": "VERDO7 IPTOS Q921 VERTI Q921 AGLUK BAREE N445A TUDEP NATU DOGAL NATU BEXET ENJEX AVZAC INFEC JETZI AMFUL OCTIZ P2 SIRIC SIRIC1H",
            "baggage_claim": "9",
            "seats_cabin_business": null,
            "seats_cabin_coach": null,
            "seats_cabin_first": null,
            "gate_origin": null,
            "gate_destination": null,
            "terminal_origin": "3",
            "terminal_destination": "5",
            "type": "Airline"
        },
        {
            "ident": "BAW92",
            "ident_icao": "BAW92",
            "ident_iata": "BA92",
            "actual_runway_off": "23",
            "actual_runway_on": "27L",
            "fa_flight_id": "BAW92-1737787430-airline-2324p",
            "operator": "BAW",
            "operator_icao": "BAW",
            "operator_iata": "BA",
            "flight_number": "92",
            "registration": "G-ZBJF",
            "atc_ident": "BAW5CA",
            "inbound_fa_flight_id": "BAW93-1737787430-airline-2325p",
            "codeshares": [
                "FIN5992",
                "EIN8792",
                "AAL6917",
                "IBE3528"
            ],
            "codeshares_iata": [
                "AY5992",
                "EI8792",
                "AA6917",
                "IB3528"
            ],
            "blocked": false,
            "diverted": false,
            "cancelled": false,
            "position_only": false,
            "origin": {
                "code": "CYYZ",
                "code_icao": "CYYZ",
                "code_iata": "YYZ",
                "code_lid": null,
                "timezone": "America/Toronto",
                "name": "Toronto Pearson Int'l",
                "city": "Toronto",
                "airport_info_url": "/airports/CYYZ"
            },
            "destination": {
                "code": "EGLL",
                "code_icao": "EGLL",
                "code_iata": "LHR",
                "code_lid": null,
                "timezone": "Europe/London",
                "name": "London Heathrow",
                "city": "London",
                "airport_info_url": "/airports/EGLL"
            },
            "departure_delay": -180,
            "arrival_delay": 60,
            "filed_ete": 22980,
            "foresight_predictions_available": true,
            "scheduled_out": "2025-01-27T23:00:00Z",
            "estimated_out": "2025-01-27T23:00:00Z",
            "actual_out": "2025-01-27T22:57:00Z",
            "scheduled_off": "2025-01-27T23:10:00Z",
            "estimated_off": "2025-01-27T23:21:20Z",
            "actual_off": "2025-01-27T23:20:00Z",
            "scheduled_on": "2025-01-28T05:33:00Z",
            "estimated_on": "2025-01-28T06:06:30Z",
            "actual_on": "2025-01-28T06:06:30Z",
            "scheduled_in": "2025-01-28T06:15:00Z",
            "estimated_in": "2025-01-28T06:12:00Z",
            "actual_in": "2025-01-28T06:16:00Z",
            "progress_percent": 100,
            "status": "Arrived / Gate Arrival",
            "aircraft_type": "B788",
            "route_distance": 3675,
            "filed_airspeed": 415,
            "filed_altitude": 330,
            "route": "VERDO7 LORKA Q907 MIILS N269A JOOPY NATS DOGAL NATS BEXET ENJEX AVZAC INFEC JETZI AMFUL OCTIZ P2 SIRIC SIRIC1H",
            "baggage_claim": "7",
            "seats_cabin_business": null,
            "seats_cabin_coach": null,
            "seats_cabin_first": null,
            "gate_origin": null,
            "gate_destination": null,
            "terminal_origin": "3",
            "terminal_destination": "5",
            "type": "Airline"
        },
        {
            "ident": "BAW92",
            "ident_icao": "BAW92",
            "ident_iata": "BA92",
            "actual_runway_off": "23",
            "actual_runway_on": "27R",
            "fa_flight_id": "BAW92-1737702878-airline-1215p",
            "operator": "BAW",
            "operator_icao": "BAW",
            "operator_iata": "BA",
            "flight_number": "92",
            "registration": "G-VIIK",
            "atc_ident": "BAW5CA",
            "inbound_fa_flight_id": "BAW93-1737702878-airline-1216p",
            "codeshares": [
                "FIN5992",
                "EIN8792",
                "AAL6917",
                "IBE3528"
            ],
            "codeshares_iata": [
                "AY5992",
                "EI8792",
                "AA6917",
                "IB3528"
            ],
            "blocked": false,
            "diverted": false,
            "cancelled": false,
            "position_only": false,
            "origin": {
                "code": "CYYZ",
                "code_icao": "CYYZ",
                "code_iata": "YYZ",
                "code_lid": null,
                "timezone": "America/Toronto",
                "name": "Toronto Pearson Int'l",
                "city": "Toronto",
                "airport_info_url": "/airports/CYYZ"
            },
            "destination": {
                "code": "EGLL",
                "code_icao": "EGLL",
                "code_iata": "LHR",
                "code_lid": null,
                "timezone": "Europe/London",
                "name": "London Heathrow",
                "city": "London",
                "airport_info_url": "/airports/EGLL"
            },
            "departure_delay": -180,
            "arrival_delay": -1560,
            "filed_ete": 23100,
            "foresight_predictions_available": true,
            "scheduled_out": "2025-01-26T23:00:00Z",
            "estimated_out": "2025-01-26T23:00:00Z",
            "actual_out": "2025-01-26T22:57:00Z",
            "scheduled_off": "2025-01-26T23:10:00Z",
            "estimated_off": "2025-01-26T23:18:11Z",
            "actual_off": "2025-01-26T23:17:00Z",
            "scheduled_on": "2025-01-27T05:35:00Z",
            "estimated_on": "2025-01-27T05:42:19Z",
            "actual_on": "2025-01-27T05:42:19Z",
            "scheduled_in": "2025-01-27T06:15:00Z",
            "estimated_in": "2025-01-27T05:48:00Z",
            "actual_in": "2025-01-27T05:49:00Z",
            "progress_percent": 100,
            "status": "Arrived / Gate Arrival",
            "aircraft_type": "B772",
            "route_distance": 3626,
            "filed_airspeed": 476,
            "filed_altitude": 370,
            "route": "VERDO7 LORKA Q907 MIILS N269A JOOPY NATS 4900N/05000W NATS DOGAL NATS BEXET BOFUM Q37 MALUD Q38 NUGRA NUGRA1H",
            "baggage_claim": "8",
            "seats_cabin_business": null,
            "seats_cabin_coach": null,
            "seats_cabin_first": null,
            "gate_origin": null,
            "gate_destination": null,
            "terminal_origin": "3",
            "terminal_destination": "5",
            "type": "Airline"
        }
    ],
    "links": null,
    "num_pages": 1
}

export const flightPositionData = {
    "ident": "BAW92",
    "ident_icao": "BAW92",
    "ident_iata": "BA92",
    "fa_flight_id": "BAW92-1738651568-airline-1208p",
    "actual_off": "2025-02-06T23:05:27Z",
    "actual_on": "2025-02-07T05:26:30Z",
    "foresight_predictions_available": true,
    "predicted_out": null,
    "predicted_off": null,
    "predicted_on": null,
    "predicted_in": null,
    "predicted_out_source": null,
    "predicted_off_source": null,
    "predicted_on_source": null,
    "predicted_in_source": null,
    "origin": {
        "code": "CYYZ",
        "code_icao": "CYYZ",
        "code_iata": "YYZ",
        "code_lid": null,
        "timezone": "America/Toronto",
        "name": "Toronto Pearson Int'l",
        "city": "Toronto",
        "airport_info_url": "/airports/CYYZ"
    },
    "destination": {
        "code": "EGLL",
        "code_icao": "EGLL",
        "code_iata": "LHR",
        "code_lid": null,
        "timezone": "Europe/London",
        "name": "London Heathrow",
        "city": "London",
        "airport_info_url": "/airports/EGLL"
    },
    "waypoints": [
        43.68,
        -79.63,
        43.7,
        -79.55,
        43.71,
        -79.5,
        43.74,
        -79.38,
        43.77,
        -79.25,
        43.81,
        -79.11,
        43.82,
        -79.08,
        43.82,
        -79.07,
        43.83,
        -78.57,
        43.85,
        -78.51,
        43.93,
        -78.29,
        43.94,
        -78.26,
        44.18,
        -77.56,
        44.2,
        -77.5,
        44.25,
        -77.38,
        44.77,
        -76.22,
        44.85,
        -75.85,
        45,
        -75.27,
        45.13,
        -74.78,
        45.24,
        -74.37,
        45.29,
        -74.2,
        45.58,
        -73.06,
        45.71,
        -72.5,
        45.85,
        -71.93,
        46.17,
        -70.57,
        46.24,
        -70.26,
        46.25,
        -70.21,
        46.87,
        -67.05,
        46.87,
        -67.05,
        47.33,
        -65.15,
        47.76,
        -63.2,
        47.79,
        -63.06,
        48.5,
        -59.35,
        48.65,
        -58.32,
        48.72,
        -57.95,
        48.77,
        -57.72,
        48.81,
        -57.52,
        49.16,
        -55.65,
        49.45,
        -53.72,
        49.47,
        -53.76,
        49.5,
        -53.5,
        49.75,
        -51.89,
        50,
        -50,
        50.42,
        -48.07,
        51.48,
        -44.67,
        52.07,
        -42.13,
        52.34,
        -40.84,
        53.3,
        -35.53,
        54,
        -30,
        54.07,
        -22.47,
        53.68,
        -15,
        53.08,
        -9.51,
        53.87,
        -7.25,
        53.6,
        -5.78,
        53.48,
        -5.5,
        53.43,
        -4.68,
        53.22,
        -3.42,
        52.92,
        -2.48,
        52.65,
        -2.1,
        52.5,
        -1.87,
        52.27,
        -1.55,
        51.51,
        -0.52,
        51.48,
        -0.46,
        51.48,
        -0.46
    ],
    "first_position_time": "2025-02-06T22:39:58Z",
    "last_position": {
        "fa_flight_id": "BAW92-1738651568-airline-1208p",
        "altitude": -2,
        "altitude_change": "D",
        "groundspeed": 0,
        "heading": 90,
        "latitude": 51.47754,
        "longitude": -0.47946,
        "timestamp": "2025-02-07T05:32:27Z",
        "update_type": "A"
    },
    "bounding_box": [
        54.9679,
        -79.81401,
        43.61637,
        -0.46059
    ],
    "ident_prefix": null,
    "aircraft_type": "B78X"
}

